import tensorflow as tf
import numpy as np
import external.poissonblending as blending
from scipy.signal import convolve2d


class ModelInpaint():
    """
    This function defines the model of Semantic Inpainting
    including:
    1. load GAN
    2. mask input images
    3. forwardpropagation and backpropagation over the model
    4. genertate output images
    """
    def __init__(self, modelfilename, config,
                 model_name='dcgan',
                 gen_input='z:0', gen_output='Tanh:0', gen_loss='Mean_2:0',
                 disc_input='real_images:0', disc_output='Sigmoid:0',
                 z_dim=100, batch_size=64):
        """
        Initialization function, takes user defined arguments to define the model structure
        
        Parameters:
        modelfilename: tensorflow .pb file with weights to be loaded
        config: training parameters: lambda_p, nIter
        gen_input: node name for generator input
        gen_output: node name for generator output
        disc_input: node name for discriminator input
        disc_output: node name for discriminator output
        z_dim - latent space dimension of GAN
        batch_size - training batch size
        """

        self.config = config

        self.batch_size = batch_size
        self.z_dim = z_dim
        self.graph, self.graph_def = ModelInpaint.loadpb(modelfilename,
                                                         model_name)
        
        # use the following self.go and self.do to load GAN for face with resolution (64, 64)
        #self.go = self.graph.get_tensor_by_name(model_name+'/'  +gen_output)
        #self.do = self.graph.get_tensor_by_name(model_name+'/' + disc_output)
        
        # use the following self.go and self.do to load other GANs
        self.go = self.graph.get_tensor_by_name(model_name+'/' + 'generator/' +gen_output)
        self.do = self.graph.get_tensor_by_name(model_name+'/'+ 'discriminator/' + disc_output)
        
        self.gi = self.graph.get_tensor_by_name(model_name+'/'+gen_input)
        self.gl = self.graph.get_tensor_by_name(model_name+'/'+gen_loss)
        self.di = self.graph.get_tensor_by_name(model_name+'/'+disc_input)
        self.image_shape = self.go.shape[1:].as_list()

        self.l = config.lambda_p

        self.sess = tf.Session(graph=self.graph)
 
        self.init_z()

    def init_z(self):
        """
        This function initializes latent space variable z
        """
        self.z = np.random.randn(self.batch_size, self.z_dim)

    def sample(self, z=None):
        """
        This function is Gan sampler, sampling images generated by GAN
        """
        if z is None:
            z = self.z
        sample_out = self.sess.run(self.go, feed_dict={self.gi: z})
        return sample_out

    def preprocess(self, images, imask, useWeightedMask = True, nsize=7):
        """
        This function performs 
        1. image preprocessing: prepare input image to feed the model
        2. mask manipulation: use input mask to generate weighted mask
                              and duplicate the weighted mask from 2D to 3D
        
        images: input images
        imask: input mask
        nsize: window size to generate weighted mask
        """
        images = ModelInpaint.imtransform(images)
        if useWeightedMask:
            mask = ModelInpaint.createWeightedMask(imask, nsize)
        else:
            mask = imask
        mask = ModelInpaint.create3ChannelMask(mask)
        

        bin_mask = ModelInpaint.binarizeMask(imask, dtype='uint8')
        self.bin_mask = ModelInpaint.create3ChannelMask(bin_mask)

        self.masks_data = np.repeat(mask[np.newaxis, :, :, :],
                                    self.batch_size,
                                    axis=0)

        #Generate multiple candidates for completion if single image is given
        if len(images.shape) is 3:
            self.images_data = np.repeat(images[np.newaxis, :, :, :],
                                         self.batch_size,
                                         axis=0)
        elif len(images.shape) is 4:
            #Ensure batch is filled
            num_images = images.shape[0]
            self.images_data = np.repeat(images[np.newaxis, 0, :, :, :],
                                         self.batch_size,
                                         axis=0)
            ncpy = min(num_images, self.batch_size)
            self.images_data[:ncpy, :, :, :] = images[:ncpy, :, :, :].copy()

    def postprocess(self, g_out, blend = True):
        """
        This function applys poisson blending using binary mask.
        
        g_out: generator output
        blend: determines what blending to use. True (default) for poisson
                blending and False to alpha blending
        """
        images_out = ModelInpaint.iminvtransform(g_out)
        images_in = ModelInpaint.iminvtransform(self.images_data)

        if blend:
            for i in range(len(g_out)):
                images_out[i] = ModelInpaint.poissonblending(
                    images_in[i], images_out[i], self.bin_mask
                )
        else:
            images_out = np.multiply(images_out, 1-self.masks_data) \
                         + np.multiply(images_in, self.masks_data)

        for i in range(len(g_out)):
            images_out[i,:,:,:] += images_in[i,0,0,0] - images_out[i,0,0,0]
        return images_out

    def build_inpaint_graph(self):
        """
        This function takes into latent variable z, mask and image to calculate 
        context loss, prior loss, and gradient on z and weight mask W
        """
        with self.graph.as_default():
            self.masks = tf.placeholder(tf.float32,
                                        [None] + self.image_shape,
                                        name='mask')
            self.images = tf.placeholder(tf.float32,
                                         [None] + self.image_shape,
                                         name='images')
            self.context_loss = tf.reduce_sum(
                    tf.contrib.layers.flatten(
                        tf.abs(tf.multiply(self.masks, self.go) -
                               tf.multiply(self.masks, self.images))), 1
                )

            self.perceptual_loss = self.gl
            self.inpaint_loss = self.context_loss + self.l*self.perceptual_loss
            self.inpaint_grad = tf.gradients(self.inpaint_loss, self.gi)
            #masks gradient
            #self.masks_grad = tf.gradients(self.context_loss, self.masks_data)

    def inpaint(self, image, mask, blend=True):
        """
        This function perform inpainting on image by calling
        
        image: input RGB image
        mask: input binary mask
        blend: boolean value to determine whether to perform poisson blending
        Return: inpainted images
        """
        self.build_inpaint_graph()
        self.preprocess(image, mask)
        imout = self.backprop_to_input()
        return self.postprocess(imout, blend), imout

    def backprop_to_input(self, verbose=True):
        """
        This function performs backpropagation to input by gradient decent to 
        obtain latent space representation of generated image, and returns
        generated output image
        """
        v = 0
        for i in range(self.config.nIter):
            #out_vars = [self.inpaint_loss, self.inpaint_grad, self.go, self.masks_grad]
            out_vars = [self.inpaint_loss, self.inpaint_grad, self.go]
            in_dict = {self.masks: self.masks_data,
                       self.gi: self.z,
                       self.images: self.images_data}

            #loss, grad, imout, masks_grad = self.sess.run(out_vars, feed_dict=in_dict)
            loss, grad, imout, masks_grad = self.sess.run(out_vars, feed_dict=in_dict)

            v_prev = np.copy(v)
            v = self.config.momentum*v - self.config.lr*grad[0]
            self.z += (-self.config.momentum * v_prev +
                       (1 + self.config.momentum) * v)
            self.z = np.clip(self.z, -1, 1)

            #update mask_data
            #self.mask_data += self.config.lr * masks_data

            if verbose:
                print('Iteration {}: {}'.format(i, np.mean(loss)))

        return imout

    @staticmethod
    def loadpb(filename, model_name='dcgan'):
        """
        This function loads in our pre-trained GAN .pb file to generate fake images
        """
        with tf.gfile.GFile(filename, 'rb') as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())

        # fix nodes
        for node in graph_def.node:
          if node.op == 'RefSwitch':
            node.op = 'Switch'
            for index in xrange(len(node.input)):
              if 'moving_' in node.input[index]:
                node.input[index] = node.input[index] + '/read'
          elif node.op == 'AssignSub':
            node.op = 'Sub'
            if 'use_locking' in node.attr: del node.attr['use_locking']



        with tf.Graph().as_default() as graph:
            tf.import_graph_def(graph_def,
                                input_map=None,
                                return_elements=None,
                                op_dict=None,
                                producer_op_list=None,
                                name=model_name)

        return graph, graph_def

    @staticmethod
    def imtransform(img):
        """
        This function rescales the pixel values into range [-1, 1]
        """
        return np.array(img) / 127.5-1

    @staticmethod
    def iminvtransform(img):
        """
         This function rescales the pixel values into range [0, 1]
        """
        return (np.array(img) + 1.0) / 2.0

    @staticmethod
    def poissonblending(img1, img2, mask):
        """
        This function calls posisson blending in ./src/external/poissonblending.py
        to blend genrated image with corrupted image.
        """
        return blending.blend(img1, img2, 1 - mask)

    @staticmethod
    def createWeightedMask(mask, nsize=7):
        """
        This function initialized weighted mask W with given input mask.
        mask: input mask numpy float32 array
        nsize: window size used to count neighborhood
        """
        ker = np.ones((nsize,nsize), dtype=np.float32)
        ker = ker/np.sum(ker)
        wmask = mask * convolve2d(mask, ker, mode='same', boundary='symm')
        return wmask

    @staticmethod
    def binarizeMask(mask, dtype=np.float32):
        """
        This function rescale the values in mask according to data type require.
        dtype = float32: return rescale mask with values in range [0,1]
        dytpe = uint8: return resclae mask with values in range [0, 255]
        
        """
        assert(np.dtype(dtype) == np.float32 or np.dtype(dtype) == np.uint8)
        bmask = np.array(mask, dtype=np.float32)
        bmask[bmask>0] = 1.0
        bmask[bmask<=0] = 0
        if dtype == np.uint8:
            bmask = np.array(bmask*255, dtype=np.uint8)
        return bmask
    
    @staticmethod
    def create3ChannelMask(mask):
        """
        create 3D mask by making copies of input 2D mask
        return: a 3D mask with shape (mask.height, mask.width, 3)
        """
        assert(len(mask.shape)==2)
        return np.repeat(mask[:,:,np.newaxis], 3, axis=2)
